install:
	cp -f  libMali.so		$(DESTDIR)/
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libEGL.so
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libEGL.so.1
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libEGL.so.1.4
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv1_CM.so
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv1_CM.so.1
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv1_CM.so.1.1
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv2.so
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv2.so.1
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv2.so.1.1
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv2.so.2
	ln -sf $(DESTDIR)/libMali.so	$(DESTDIR)/libGLESv2.so.2.0.0
